line-length = 200
target-version = "py312"

[lint]
select = ["E","F","I","UP","B","SIM","PL","NPY","PD"]
# Let this is already set via line-length above so ignore line-length rule
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"