name: Promote to Production

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      service:
        required: true
        type: string
      type:
        required: true
        type: string
      environment:
        required: true
        type: string

env:
  PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID_QA }}
  REGISTRY_QA: us-east4-docker.pkg.dev/agile-alignment-340016/images
  REGISTRY: us-east4-docker.pkg.dev/athliance-prod/images
  REPOSITORY: ${{ inputs.repository }}
  SERVICE: ${{ inputs.service }}
  TYPE: ${{ inputs.type }}
  ENVIRONMENT: ${{ inputs.environment }}

jobs:
  prod-deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    # ------------- IMPORTANT ----------------
    # This is what ensures there is a check before the job is
    # run within github (forces the button to be manual)
    # https://docs.github.com/en/actions/reference/workflows-and-actions/deployments-and-environments#deployment-protection-rules
    environment:
      name: prod
    steps:
      # TODO: Configure steps to deploy lambda/function